SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_localizacao'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_necessidade'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_familia_beneficiaria'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_cota_agua'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE seq_localizacao START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_necessidade START WITH 200 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_familia_beneficiaria START WITH 5000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_cota_agua START WITH 6000 INCREMENT BY 1 NOCACHE NOCYCLE;
