SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE SESSAO_FUNCIONARIO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SESSAO_SISTEMA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NO_SISTEMA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE NO_SISTEMA (
    codigo_no    NUMBER(7) NOT NULL,
    nome_no      VARCHAR2(60) NOT NULL,
    host_no      VARCHAR2(100) NULL,
    estado_no    VARCHAR2(20) DEFAULT 'Activo' NOT NULL
);

ALTER TABLE NO_SISTEMA ADD CONSTRAINT pk_no_sistema PRIMARY KEY (codigo_no);
ALTER TABLE NO_SISTEMA ADD CONSTRAINT uk_no_sistema_nome UNIQUE (nome_no);
ALTER TABLE NO_SISTEMA ADD CONSTRAINT ck_no_sistema_estado CHECK (estado_no IN ('Activo', 'Inactivo'));

CREATE TABLE FUNCIONARIO (
    cod_funcionario NUMBER(7) NOT NULL,
    codigo_no          NUMBER(7) NOT NULL,
    nome_funcionario   VARCHAR2(100) NOT NULL,
    username_oracle    VARCHAR2(30) NOT NULL,
    estado_funcionario VARCHAR2(20) DEFAULT 'Activo' NOT NULL
);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT pk_funcionario PRIMARY KEY (cod_funcionario);
ALTER TABLE FUNCIONARIO ADD CONSTRAINT uk_funcionario_username UNIQUE (username_oracle);
ALTER TABLE FUNCIONARIO ADD CONSTRAINT ck_funcionario_estado CHECK (estado_funcionario IN ('Activo', 'Inactivo'));
ALTER TABLE FUNCIONARIO
    ADD CONSTRAINT fk_funcionario_no FOREIGN KEY (codigo_no)
    REFERENCES NO_SISTEMA (codigo_no);

CREATE TABLE SESSAO_FUNCIONARIO (
    codigo_sessao      NUMBER(7) NOT NULL,
    cod_funcionario    NUMBER(7) NOT NULL,
    codigo_no          NUMBER(7) NOT NULL,
    data_inicio        DATE DEFAULT SYSDATE NOT NULL,
    data_fim           DATE NULL,
    estado_sessao      VARCHAR2(20) DEFAULT 'ABERTA' NOT NULL,
    modo_login         VARCHAR2(20) DEFAULT 'ONLINE' NOT NULL
);

ALTER TABLE SESSAO_FUNCIONARIO ADD CONSTRAINT pk_sessao_funcionario PRIMARY KEY (codigo_sessao);
ALTER TABLE SESSAO_FUNCIONARIO ADD CONSTRAINT ck_sessao_estado CHECK (estado_sessao IN ('ABERTA', 'FECHADA', 'EXPIRADA'));
ALTER TABLE SESSAO_FUNCIONARIO ADD CONSTRAINT ck_sessao_modo CHECK (modo_login IN ('ONLINE', 'OFFLINE'));
ALTER TABLE SESSAO_FUNCIONARIO
    ADD CONSTRAINT fk_sessao_funcionario FOREIGN KEY (cod_funcionario)
    REFERENCES FUNCIONARIO (cod_funcionario);
ALTER TABLE SESSAO_FUNCIONARIO
    ADD CONSTRAINT fk_sessao_no FOREIGN KEY (codigo_no)
    REFERENCES NO_SISTEMA (codigo_no);

CREATE UNIQUE INDEX uk_sessao_aberta_func
    ON SESSAO_FUNCIONARIO (
        CASE WHEN estado_sessao = 'ABERTA' THEN cod_funcionario ELSE NULL END
    );
