SET ECHO OFF;

DECLARE
    v_sql VARCHAR2(300);
BEGIN
    FOR s IN (
        SELECT sid, serial#
          FROM v$session
         WHERE username IN ('ADM_OWNER', 'ADM_FUNC_01', 'ADM_FUNC_02', 'APP_LOGIN_ADMIN')
    ) LOOP
        BEGIN
            v_sql := 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
            EXECUTE IMMEDIATE v_sql;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP ROLE ADM_FUNC_02'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ADM_FUNC_01'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ADM_OWNER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP USER ADM_FUNC_02 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER ADM_FUNC_01 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER APP_LOGIN_ADMIN CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER ADM_OWNER CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE R_ADM_FUNC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE USER ADM_OWNER IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_ADMINISTRADOR
TEMPORARY TABLESPACE TEMP
QUOTA 300M ON TS_ADMINISTRADOR;

GRANT CREATE SESSION TO ADM_OWNER WITH ADMIN OPTION;
GRANT CREATE TABLE TO ADM_OWNER;
GRANT CREATE VIEW TO ADM_OWNER;
GRANT CREATE SEQUENCE TO ADM_OWNER;
GRANT CREATE PROCEDURE TO ADM_OWNER;
GRANT CREATE TRIGGER TO ADM_OWNER;
GRANT CREATE MATERIALIZED VIEW TO ADM_OWNER;
GRANT CREATE DATABASE LINK TO ADM_OWNER;
GRANT CREATE SYNONYM TO ADM_OWNER;
GRANT CREATE PUBLIC SYNONYM TO ADM_OWNER;
GRANT DROP PUBLIC SYNONYM TO ADM_OWNER;
GRANT CREATE USER TO ADM_OWNER;
GRANT ALTER USER TO ADM_OWNER;

CREATE ROLE R_ADM_FUNC;

GRANT R_ADM_FUNC TO ADM_OWNER WITH ADMIN OPTION;

CREATE USER APP_LOGIN_ADMIN IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_ADMINISTRADOR
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_ADMINISTRADOR;

GRANT CREATE SESSION TO APP_LOGIN_ADMIN;

CREATE USER ADM_FUNC_01 IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_ADMINISTRADOR
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_ADMINISTRADOR;

CREATE USER ADM_FUNC_02 IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_ADMINISTRADOR
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_ADMINISTRADOR;

GRANT CREATE SESSION TO ADM_FUNC_01;
GRANT CREATE SESSION TO ADM_FUNC_02;

GRANT R_ADM_FUNC TO ADM_FUNC_01;
GRANT R_ADM_FUNC TO ADM_FUNC_02;
