SET ECHO OFF;

-- Links privados deste owner para os outros nos.

BEGIN EXECUTE IMMEDIATE 'DROP DATABASE LINK DBLINK_FAM_COTAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP DATABASE LINK DBLINK_DIST_CONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP DATABASE LINK DBLINK_TRANSF_REC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP DATABASE LINK DBLINK_EQ_GESTAO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE DATABASE LINK DBLINK_FAM_COTAS
CONNECT TO FAM_REMOTE_ADM IDENTIFIED BY "20240629"
USING 'CENTOS_1_FamiliasCotas';

CREATE DATABASE LINK DBLINK_DIST_CONS
CONNECT TO DIST_REMOTE_ADM IDENTIFIED BY "20240629"
USING 'CENTOS_2_DistribuicaoConsumo';

CREATE DATABASE LINK DBLINK_TRANSF_REC
CONNECT TO TRANS_REMOTE_ADM IDENTIFIED BY "20240629"
USING 'CENTOS_3_TransferenciasRecursos';

CREATE DATABASE LINK DBLINK_EQ_GESTAO
CONNECT TO EQ_REMOTE_ADM IDENTIFIED BY "20240629"
USING 'CENTOS_4_EquipesGestao';
