SET ECHO OFF;

-- Utilizador remoto e grants minimos para DistribuicaoConsumoDB.

BEGIN
    FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'ADM_REMOTE_DIST') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    EXECUTE IMMEDIATE 'DROP USER ADM_REMOTE_DIST CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER ADM_REMOTE_DIST IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_ADMINISTRADOR
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_ADMINISTRADOR;

GRANT CREATE SESSION TO ADM_REMOTE_DIST;
GRANT SELECT ON ADM_OWNER.FUNCIONARIO TO ADM_REMOTE_DIST;
