SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SESSAO_FUNCIONARIO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SESSAO_SISTEMA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FUNCIONARIO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NO_SISTEMA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE SEQ_NO_SISTEMA START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FUNCIONARIO START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SESSAO_FUNCIONARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
