SET ECHO OFF;

SET DEFINE OFF;

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Familia_Beneficiaria'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Cota_Agua_Status'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Familia_Cota'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Ponto_Distribuicao'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Registro_Consumo'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Historico_Abastecimento'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Recurso_Hidrico'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM RH_Qualidade_Agua'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM TESTE_CONEXAO_FAM_COTAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM TESTE_CONEXAO_DIST_CONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM TESTE_CONEXAO_TRANS_REC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM TESTE_CONEXAO_EQ_GESTAO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE OR REPLACE SYNONYM Familia_Beneficiaria
FOR FAM_OWNER.VW_FAMILIA_BENEFICIARIA@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM Cota_Agua_Status
FOR FAM_OWNER.VW_COTA_AGUA_STATUS@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM Familia_Cota
FOR FAM_OWNER.VW_FAMILIA_COTA@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM Ponto_Distribuicao
FOR DIST_OWNER.VW_PONTO_DISTRIBUICAO@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM Registro_Consumo
FOR DIST_OWNER.VW_REGISTRO_CONSUMO@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM Historico_Abastecimento
FOR DIST_OWNER.VW_HISTORICO_ABASTECIMENTO@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM Recurso_Hidrico
FOR TRANS_OWNER.VW_RECURSO_HIDRICO@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM RH_Qualidade_Agua
FOR TRANS_OWNER.VW_RH_QUALIDADE_AGUA@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_FAM_COTAS
FOR DUAL@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_DIST_CONS
FOR DUAL@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_TRANS_REC
FOR DUAL@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_EQ_GESTAO
FOR DUAL@DBLINK_EQ_GESTAO;

CREATE OR REPLACE PUBLIC SYNONYM VW_LOGIN_FUNCIONARIO_ADMIN
FOR ADM_OWNER.VW_LOGIN_FUNCIONARIO_ADMIN;

CREATE OR REPLACE PUBLIC SYNONYM VW_LOGIN_NO_ADMIN
FOR ADM_OWNER.VW_LOGIN_NO_ADMIN;
