SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_NO_SISTEMA_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_FUNCIONARIO_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_SESSAO_FUNCIONARIO_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_SESSAO_SISTEMA_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE OR REPLACE TRIGGER TRG_NO_SISTEMA_BI
BEFORE INSERT ON NO_SISTEMA
FOR EACH ROW
BEGIN
    IF :NEW.codigo_no IS NULL THEN
        SELECT SEQ_NO_SISTEMA.NEXTVAL INTO :NEW.codigo_no FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_FUNCIONARIO_BI
BEFORE INSERT ON FUNCIONARIO
FOR EACH ROW
BEGIN
    IF :NEW.cod_funcionario IS NULL THEN
        SELECT SEQ_FUNCIONARIO.NEXTVAL INTO :NEW.cod_funcionario FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SESSAO_FUNCIONARIO_BI
BEFORE INSERT ON SESSAO_FUNCIONARIO
FOR EACH ROW
BEGIN
    IF :NEW.codigo_sessao IS NULL THEN
        SELECT SEQ_SESSAO_FUNCIONARIO.NEXTVAL INTO :NEW.codigo_sessao FROM DUAL;
    END IF;
END;
/
