SET ECHO OFF;

SET DEFINE OFF;

BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_FUNCIONARIOS_ADMINISTRADOR'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_FUNC_ADMIN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_FUNCIONARIOS_FAMILIAS_COTAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_FUNC_FAM_COTAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_FUNCIONARIOS_DISTRIBUICAO_CONSUMO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_FUNC_DIST_CONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_FUNCIONARIOS_TRANSFERENCIAS_RECURSOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_FUNC_TRANSF_REC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_FUNCIONARIOS_EQUIPES_GESTAO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_FUNC_EQ_GESTAO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_LOGIN_FUNCIONARIO_ADMIN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_LOGIN_NO_ADMIN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_NO_SISTEMA_ACTIVO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_FUNCIONARIO_LISTAGEM'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_ALERTA_QUALIDADE_ADMIN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_DASH_FUNCIONARIO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_DASH_SESSAO_ADMIN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_DASH_FUNCIONARIOS_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_DASH_SESSOES_ESTADO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_DASH_NOS_REGISTADOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_CONEXAO_FAM_COTAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_CONEXAO_DIST_CONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_CONEXAO_TRANS_REC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_CONEXAO_EQ_GESTAO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE OR REPLACE VIEW VW_FUNC_ADMIN AS
SELECT *
FROM FUNCIONARIO
WHERE codigo_no = 1;

CREATE OR REPLACE VIEW VW_FUNC_FAM_COTAS AS
SELECT *
FROM FUNCIONARIO
WHERE codigo_no = 2;

CREATE OR REPLACE VIEW VW_FUNC_DIST_CONS AS
SELECT *
FROM FUNCIONARIO
WHERE codigo_no = 3;

CREATE OR REPLACE VIEW VW_FUNC_TRANSF_REC AS
SELECT *
FROM FUNCIONARIO
WHERE codigo_no = 4;

CREATE OR REPLACE VIEW VW_FUNC_EQ_GESTAO AS
SELECT *
FROM FUNCIONARIO
WHERE codigo_no = 5;

CREATE OR REPLACE VIEW VW_LOGIN_FUNCIONARIO_ADMIN AS
SELECT cod_funcionario,
       codigo_no,
       nome_funcionario,
       username_oracle,
       estado_funcionario
  FROM FUNCIONARIO;

CREATE OR REPLACE VIEW VW_LOGIN_NO_ADMIN AS
SELECT codigo_no,
       nome_no,
       estado_no
  FROM NO_SISTEMA;

CREATE OR REPLACE VIEW VW_NO_SISTEMA_ACTIVO AS
SELECT codigo_no,
       nome_no,
       host_no,
       estado_no
  FROM NO_SISTEMA
 WHERE UPPER(TRIM(estado_no)) = 'ACTIVO';

CREATE OR REPLACE VIEW VW_FUNCIONARIO_LISTAGEM AS
SELECT f.cod_funcionario,
       f.nome_funcionario,
       f.username_oracle,
       n.nome_no,
       f.estado_funcionario
  FROM FUNCIONARIO f
  JOIN NO_SISTEMA n
    ON n.codigo_no = f.codigo_no;

CREATE OR REPLACE VIEW VW_ALERTA_QUALIDADE_ADMIN AS
SELECT codigo_alerta,
       codigo_medicao,
       codigo_rh,
       mensagem_alerta,
       data_alerta
  FROM MV_ALERTA_QUALIDADE_AGUA_ADMIN;

CREATE OR REPLACE VIEW VW_DASH_FUNCIONARIO AS
SELECT f.cod_funcionario,
       f.codigo_no,
       n.nome_no,
       f.nome_funcionario,
       f.username_oracle,
       f.estado_funcionario
  FROM FUNCIONARIO f
  JOIN NO_SISTEMA n
    ON n.codigo_no = f.codigo_no;

CREATE OR REPLACE VIEW VW_DASH_SESSAO_ADMIN AS
SELECT codigo_sessao,
       cod_funcionario,
       codigo_no,
       data_inicio,
       data_fim,
       estado_sessao,
       modo_login
  FROM SESSAO_FUNCIONARIO;

CREATE OR REPLACE VIEW VW_DASH_FUNCIONARIOS_NO AS
SELECT n.nome_no,
       'funcionarios registados' AS descricao,
       TO_CHAR(COUNT(f.cod_funcionario)) AS total
  FROM NO_SISTEMA n
  LEFT JOIN FUNCIONARIO f
    ON f.codigo_no = n.codigo_no
 GROUP BY n.nome_no;

CREATE OR REPLACE VIEW VW_DASH_SESSOES_ESTADO AS
SELECT estado_sessao,
       'total no historico administrativo' AS descricao,
       TO_CHAR(COUNT(*)) AS total
  FROM SESSAO_FUNCIONARIO
 GROUP BY estado_sessao;

CREATE OR REPLACE VIEW VW_DASH_NOS_REGISTADOS AS
SELECT nome_no,
       NVL(host_no, 'sem host configurado') AS host_no,
       estado_no,
       codigo_no
  FROM NO_SISTEMA;

CREATE OR REPLACE FORCE VIEW VW_CONEXAO_FAM_COTAS AS
SELECT 1 AS estado_conexao
  FROM TESTE_CONEXAO_FAM_COTAS;

CREATE OR REPLACE FORCE VIEW VW_CONEXAO_DIST_CONS AS
SELECT 1 AS estado_conexao
  FROM TESTE_CONEXAO_DIST_CONS;

CREATE OR REPLACE FORCE VIEW VW_CONEXAO_TRANS_REC AS
SELECT 1 AS estado_conexao
  FROM TESTE_CONEXAO_TRANS_REC;

CREATE OR REPLACE FORCE VIEW VW_CONEXAO_EQ_GESTAO AS
SELECT 1 AS estado_conexao
  FROM TESTE_CONEXAO_EQ_GESTAO;

ALTER VIEW VW_CONEXAO_FAM_COTAS COMPILE;
ALTER VIEW VW_CONEXAO_DIST_CONS COMPILE;
ALTER VIEW VW_CONEXAO_TRANS_REC COMPILE;
ALTER VIEW VW_CONEXAO_EQ_GESTAO COMPILE;
