SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP USER TRANS_FUNC_02 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER TRANS_FUNC_01 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER APP_LOGIN_TRANS CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER TRANS_OWNER CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER E20240629 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE R_TRANS_FUNC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE USER TRANS_OWNER IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_TRANSFERENCIAS_RECURSOS
TEMPORARY TABLESPACE TEMP
QUOTA 300M ON TS_TRANSFERENCIAS_RECURSOS;

GRANT CREATE SESSION TO TRANS_OWNER WITH ADMIN OPTION;
GRANT CREATE TABLE TO TRANS_OWNER;
GRANT CREATE VIEW TO TRANS_OWNER;
GRANT CREATE SEQUENCE TO TRANS_OWNER;
GRANT CREATE PROCEDURE TO TRANS_OWNER;
GRANT CREATE TRIGGER TO TRANS_OWNER;
GRANT CREATE SNAPSHOT TO TRANS_OWNER;
GRANT CREATE DATABASE LINK TO TRANS_OWNER;
GRANT CREATE SYNONYM TO TRANS_OWNER;
GRANT CREATE PUBLIC SYNONYM TO TRANS_OWNER;
GRANT DROP PUBLIC SYNONYM TO TRANS_OWNER;
GRANT CREATE USER TO TRANS_OWNER;
GRANT ALTER USER TO TRANS_OWNER;

CREATE ROLE R_TRANS_FUNC;

GRANT R_TRANS_FUNC TO TRANS_OWNER WITH ADMIN OPTION;

CREATE USER APP_LOGIN_TRANS IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_TRANSFERENCIAS_RECURSOS
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_TRANSFERENCIAS_RECURSOS;

GRANT CREATE SESSION TO APP_LOGIN_TRANS;

CREATE USER TRANS_FUNC_01 IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_TRANSFERENCIAS_RECURSOS
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_TRANSFERENCIAS_RECURSOS;

CREATE USER TRANS_FUNC_02 IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_TRANSFERENCIAS_RECURSOS
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_TRANSFERENCIAS_RECURSOS;

GRANT CREATE SESSION TO TRANS_FUNC_01;
GRANT CREATE SESSION TO TRANS_FUNC_02;

GRANT R_TRANS_FUNC TO TRANS_FUNC_01;
GRANT R_TRANS_FUNC TO TRANS_FUNC_02;
