SET ECHO OFF;

BEGIN
    FOR r IN (
        SELECT object_name
        FROM user_objects
        WHERE object_type IN ('VIEW', 'MATERIALIZED VIEW')
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'GRANT SELECT ON ' || r.object_name || ' TO R_TRANS_FUNC';
            EXECUTE IMMEDIATE 'GRANT SELECT ON ' || r.object_name || ' TO TRANS_FUNC_01';
            EXECUTE IMMEDIATE 'GRANT SELECT ON ' || r.object_name || ' TO TRANS_FUNC_02';
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

BEGIN
    FOR r IN (
        SELECT object_name
        FROM user_objects
        WHERE object_type IN ('PROCEDURE', 'FUNCTION')
    ) LOOP
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON ' || r.object_name || ' TO R_TRANS_FUNC';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON ' || r.object_name || ' TO TRANS_FUNC_01';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON ' || r.object_name || ' TO TRANS_FUNC_02';
    END LOOP;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON TRANS_OWNER.VW_ANALISTA_QUALIDADE TO R_TRANS_FUNC';
    EXECUTE IMMEDIATE 'GRANT SELECT ON TRANS_OWNER.VW_ANALISTA_QUALIDADE TO TRANS_FUNC_01';
    EXECUTE IMMEDIATE 'GRANT SELECT ON TRANS_OWNER.VW_ANALISTA_QUALIDADE TO TRANS_FUNC_02';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

GRANT SELECT ON TRANS_OWNER.VW_LOGIN_FUNCIONARIO_LOCAL TO APP_LOGIN_TRANS;
GRANT SELECT ON TRANS_OWNER.VW_TESTE_CONEXAO_FAM_COTAS TO R_TRANS_FUNC;
GRANT SELECT ON TRANS_OWNER.VW_TESTE_CONEXAO_DIST_CONS TO R_TRANS_FUNC;
GRANT SELECT ON TRANS_OWNER.VW_TESTE_CONEXAO_EQ_GESTAO TO R_TRANS_FUNC;

SET ECHO OFF;
