SET ECHO OFF;

-- Utilizador remoto e grants minimos para FamiliasCotasDB.

BEGIN
    FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'TRANS_REMOTE_FAM') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    EXECUTE IMMEDIATE 'DROP USER TRANS_REMOTE_FAM CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER TRANS_REMOTE_FAM IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_TRANSFERENCIAS_RECURSOS
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_TRANSFERENCIAS_RECURSOS;

GRANT CREATE SESSION TO TRANS_REMOTE_FAM;

GRANT SELECT ON TRANS_OWNER.VW_TRANSFERENCIA_COTA TO TRANS_REMOTE_FAM;
GRANT SELECT ON TRANS_OWNER.VW_FAMILIA_DOA_REC_TRANSFER TO TRANS_REMOTE_FAM;
GRANT SELECT ON TRANS_OWNER.VW_TRANSFER_ASSOC_COTA TO TRANS_REMOTE_FAM;
GRANT EXECUTE ON TRANS_OWNER.FN_EXISTE_TRANSFER_FAMILIA TO TRANS_REMOTE_FAM;
GRANT EXECUTE ON TRANS_OWNER.PRC_TRANSFERIR_COTA TO TRANS_REMOTE_FAM;
