SET ECHO OFF;

-- Utilizador remoto e grants minimos para EquipesGestaoDB.

BEGIN
    FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'TRANS_REMOTE_EQ') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    EXECUTE IMMEDIATE 'DROP USER TRANS_REMOTE_EQ CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER TRANS_REMOTE_EQ IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_TRANSFERENCIAS_RECURSOS
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_TRANSFERENCIAS_RECURSOS;

GRANT CREATE SESSION TO TRANS_REMOTE_EQ;

GRANT SELECT ON TRANS_OWNER.VW_PARAMETRO_QUALIDADE TO TRANS_REMOTE_EQ;
GRANT SELECT ON TRANS_OWNER.VW_ALERTA_QUALIDADE_AGUA TO TRANS_REMOTE_EQ;
GRANT SELECT ON TRANS_OWNER.Alerta_Qualidade_Agua TO TRANS_REMOTE_EQ;
GRANT SELECT, INSERT ON TRANS_OWNER.Parametro_Qualidade TO TRANS_REMOTE_EQ;
GRANT SELECT ON TRANS_OWNER.seq_parametro_qualidade TO TRANS_REMOTE_EQ;
GRANT EXECUTE ON TRANS_OWNER.PRC_REG_PARAM_QUALIDADE_EQ TO TRANS_REMOTE_EQ;
