SET ECHO OFF;

-- Utilizador remoto e grants minimos para AdministradorDB.

BEGIN
    FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'TRANS_REMOTE_ADM') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    EXECUTE IMMEDIATE 'DROP USER TRANS_REMOTE_ADM CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER TRANS_REMOTE_ADM IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_TRANSFERENCIAS_RECURSOS
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_TRANSFERENCIAS_RECURSOS;

GRANT CREATE SESSION TO TRANS_REMOTE_ADM;

GRANT SELECT ON TRANS_OWNER.VW_RECURSO_HIDRICO TO TRANS_REMOTE_ADM;
GRANT SELECT ON TRANS_OWNER.VW_RH_QUALIDADE_AGUA TO TRANS_REMOTE_ADM;
GRANT SELECT ON TRANS_OWNER.VW_ALERTA_QUALIDADE_AGUA TO TRANS_REMOTE_ADM;
GRANT SELECT ON TRANS_OWNER.Alerta_Qualidade_Agua TO TRANS_REMOTE_ADM;
GRANT SELECT ON TRANS_OWNER.VW_AUDITORIA_SESSOES_LOCAL TO TRANS_REMOTE_ADM;
GRANT SELECT ON TRANS_OWNER.SESSAO_FUNCIONARIO_LOCAL TO TRANS_REMOTE_ADM;
GRANT SELECT ON TRANS_OWNER.MV_FUNCIONARIO_LOCAL TO TRANS_REMOTE_ADM;
GRANT EXECUTE ON TRANS_OWNER.PRC_REFRESH_FUNCIONARIO_LOCAL TO TRANS_REMOTE_ADM;
GRANT EXECUTE ON TRANS_OWNER.PRC_FECHAR_SESSAO_FUNC_LOCAL TO TRANS_REMOTE_ADM;
