SET ECHO OFF;

-- Utilizador remoto e grants minimos para DistribuicaoConsumoDB.

BEGIN
    FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'TRANS_REMOTE_DIST') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    EXECUTE IMMEDIATE 'DROP USER TRANS_REMOTE_DIST CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER TRANS_REMOTE_DIST IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_TRANSFERENCIAS_RECURSOS
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_TRANSFERENCIAS_RECURSOS;

GRANT CREATE SESSION TO TRANS_REMOTE_DIST;

GRANT SELECT ON TRANS_OWNER.VW_RECURSO_HIDRICO TO TRANS_REMOTE_DIST;
GRANT EXECUTE ON TRANS_OWNER.PRC_VALIDAR_RECURSO_DIST TO TRANS_REMOTE_DIST;
