SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Funcionario'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Familia_Beneficiaria'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Cota_Agua'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Analista_Qualidade'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Ponto_Distribuicao'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Historico_Abastecimento'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM PRC_APLICAR_TRANSF_COTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM PRC_VAL_ANALISTAS_TRANS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM TESTE_CONEXAO_FAM_COTAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM TESTE_CONEXAO_FAM_COTAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM TESTE_CONEXAO_DIST_CONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM TESTE_CONEXAO_DIST_CONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM TESTE_CONEXAO_EQ_GESTAO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM TESTE_CONEXAO_EQ_GESTAO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
    FOR r IN (
        SELECT object_name
        FROM user_objects
        WHERE object_type IN ('VIEW', 'PROCEDURE', 'FUNCTION', 'MATERIALIZED VIEW')
          AND object_name NOT LIKE 'BIN$%'
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM ' || r.object_name;
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

CREATE OR REPLACE SYNONYM Funcionario
FOR ADM_OWNER.FUNCIONARIO@DBLINK_ADMIN;

CREATE OR REPLACE SYNONYM Familia_Beneficiaria
FOR FAM_OWNER.VW_FAMILIA_BENEFICIARIA@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM Cota_Agua
FOR FAM_OWNER.VW_COTA_AGUA@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM PRC_APLICAR_TRANSF_COTA
FOR FAM_OWNER.PRC_APLICAR_TRANSF_COTA@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM Analista_Qualidade
FOR EQ_OWNER.VW_ANALISTA_QUALIDADE@DBLINK_EQ_GESTAO;

CREATE OR REPLACE SYNONYM PRC_VAL_ANALISTAS_TRANS
FOR EQ_OWNER.PRC_VAL_ANALISTAS_TRANS@DBLINK_EQ_GESTAO;

CREATE OR REPLACE SYNONYM Ponto_Distribuicao
FOR DIST_OWNER.VW_PONTO_DISTRIBUICAO@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM Historico_Abastecimento
FOR DIST_OWNER.VW_HISTORICO_ABASTECIMENTO@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_FAM_COTAS
FOR DUAL@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_DIST_CONS
FOR DUAL@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_EQ_GESTAO
FOR DUAL@DBLINK_EQ_GESTAO;

CREATE OR REPLACE PUBLIC SYNONYM TESTE_CONEXAO_FAM_COTAS
FOR TRANS_OWNER.VW_TESTE_CONEXAO_FAM_COTAS;

CREATE OR REPLACE PUBLIC SYNONYM TESTE_CONEXAO_DIST_CONS
FOR TRANS_OWNER.VW_TESTE_CONEXAO_DIST_CONS;

CREATE OR REPLACE PUBLIC SYNONYM TESTE_CONEXAO_EQ_GESTAO
FOR TRANS_OWNER.VW_TESTE_CONEXAO_EQ_GESTAO;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_objects
     WHERE object_name = 'VW_ANALISTA_QUALIDADE'
       AND object_type = 'VIEW';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER VIEW VW_ANALISTA_QUALIDADE COMPILE';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

DECLARE
    v_owner VARCHAR2(30) := USER;
BEGIN
    FOR r IN (
        SELECT object_name
        FROM user_objects
        WHERE object_type IN ('VIEW', 'PROCEDURE', 'FUNCTION', 'MATERIALIZED VIEW')
          AND object_name NOT LIKE 'BIN$%'
    ) LOOP
        EXECUTE IMMEDIATE 'CREATE PUBLIC SYNONYM ' || r.object_name || ' FOR ' || v_owner || '.' || r.object_name;
    END LOOP;
END;
/

CREATE OR REPLACE PUBLIC SYNONYM VW_LOGIN_FUNCIONARIO_LOCAL
FOR TRANS_OWNER.VW_LOGIN_FUNCIONARIO_LOCAL;
