SET ECHO OFF;

CREATE TABLESPACE TS_TRANSFERENCIAS_RECURSOS
DATAFILE '/usr/lib/oracle/xe/oradata/XE/ts_transferencias_recursos01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 25M MAXSIZE 300M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
