SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP USER EQ_FUNC_02 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER EQ_FUNC_01 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER APP_LOGIN_EQ CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER EQ_OWNER CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER E20240629 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE R_EQ_FUNC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE USER EQ_OWNER IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_EQUIPES_GESTAO
TEMPORARY TABLESPACE TEMP
QUOTA 250M ON TS_EQUIPES_GESTAO;

GRANT CREATE SESSION TO EQ_OWNER WITH ADMIN OPTION;
GRANT CREATE TABLE TO EQ_OWNER;
GRANT CREATE VIEW TO EQ_OWNER;
GRANT CREATE SEQUENCE TO EQ_OWNER;
GRANT CREATE PROCEDURE TO EQ_OWNER;
GRANT CREATE TRIGGER TO EQ_OWNER;
GRANT CREATE SNAPSHOT TO EQ_OWNER;
GRANT CREATE MATERIALIZED VIEW TO EQ_OWNER;
GRANT CREATE DATABASE LINK TO EQ_OWNER;
GRANT CREATE SYNONYM TO EQ_OWNER;
GRANT CREATE PUBLIC SYNONYM TO EQ_OWNER;
GRANT DROP PUBLIC SYNONYM TO EQ_OWNER;
GRANT CREATE USER TO EQ_OWNER;
GRANT ALTER USER TO EQ_OWNER;

CREATE ROLE R_EQ_FUNC;

GRANT R_EQ_FUNC TO EQ_OWNER WITH ADMIN OPTION;

CREATE USER APP_LOGIN_EQ IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_EQUIPES_GESTAO
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_EQUIPES_GESTAO;

GRANT CREATE SESSION TO APP_LOGIN_EQ;

CREATE USER EQ_FUNC_01 IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_EQUIPES_GESTAO
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_EQUIPES_GESTAO;

CREATE USER EQ_FUNC_02 IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_EQUIPES_GESTAO
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_EQUIPES_GESTAO;

GRANT CREATE SESSION TO EQ_FUNC_01;
GRANT CREATE SESSION TO EQ_FUNC_02;

GRANT R_EQ_FUNC TO EQ_FUNC_01;
GRANT R_EQ_FUNC TO EQ_FUNC_02;
