SET ECHO OFF;

-- Links privados deste owner para os outros nos.

BEGIN EXECUTE IMMEDIATE 'DROP DATABASE LINK DBLINK_ADMIN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP DATABASE LINK DBLINK_DIST_CONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP DATABASE LINK DBLINK_TRANSF_REC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE DATABASE LINK DBLINK_ADMIN
CONNECT TO ADM_REMOTE_EQ IDENTIFIED BY "20240629"
USING 'CENTOS_5_Administrador';

CREATE DATABASE LINK DBLINK_DIST_CONS
CONNECT TO DIST_REMOTE_EQ IDENTIFIED BY "20240629"
USING 'CENTOS_2_DistribuicaoConsumo';

CREATE DATABASE LINK DBLINK_TRANSF_REC
CONNECT TO TRANS_REMOTE_EQ IDENTIFIED BY "20240629"
USING 'CENTOS_3_TransferenciasRecursos';
