SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP SNAPSHOT MV_FUNCIONARIO_LOCAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW MV_ALERTA_QUALIDADE_AGUA';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE SNAPSHOT MV_FUNCIONARIO_LOCAL
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
    cod_funcionario,
    codigo_no,
    nome_funcionario,
    username_oracle,
    estado_funcionario
FROM Funcionario
WHERE codigo_no = 5;

CREATE MATERIALIZED VIEW MV_ALERTA_QUALIDADE_AGUA
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT codigo_alerta,
       codigo_medicao,
       codigo_rh,
       mensagem_alerta,
       data_alerta
  FROM TRANS_OWNER.Alerta_Qualidade_Agua@DBLINK_TRANSF_REC;
