SET ECHO OFF;

-- Utilizador remoto e grants minimos para TransferenciasRecursosDB.

BEGIN
    FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'EQ_REMOTE_TRANS') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    EXECUTE IMMEDIATE 'DROP USER EQ_REMOTE_TRANS CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER EQ_REMOTE_TRANS IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_EQUIPES_GESTAO
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_EQUIPES_GESTAO;

GRANT CREATE SESSION TO EQ_REMOTE_TRANS;

ALTER VIEW EQ_OWNER.VW_ANALISTA_QUALIDADE COMPILE;

GRANT SELECT ON EQ_OWNER.VW_ANALISTA_QUALIDADE TO EQ_REMOTE_TRANS;
GRANT EXECUTE ON EQ_OWNER.PRC_VAL_ANALISTAS_TRANS TO EQ_REMOTE_TRANS;
