SET ECHO OFF;

-- Utilizador remoto e grants minimos para DistribuicaoConsumoDB.

BEGIN
    FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'EQ_REMOTE_DIST') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    EXECUTE IMMEDIATE 'DROP USER EQ_REMOTE_DIST CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER EQ_REMOTE_DIST IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_EQUIPES_GESTAO
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_EQUIPES_GESTAO;

GRANT CREATE SESSION TO EQ_REMOTE_DIST;

GRANT SELECT ON EQ_OWNER.VW_COMITE TO EQ_REMOTE_DIST;
GRANT SELECT ON EQ_OWNER.VW_EQUIPE_TECNICA TO EQ_REMOTE_DIST;
GRANT SELECT ON EQ_OWNER.VW_TECNICO_MANUTENCAO TO EQ_REMOTE_DIST;
GRANT EXECUTE ON EQ_OWNER.PRC_VALIDAR_COMITE_DIST TO EQ_REMOTE_DIST;
GRANT EXECUTE ON EQ_OWNER.PRC_VALIDAR_TECNICO_MANUT_DIST TO EQ_REMOTE_DIST;
