-- Utilizador remoto e grants minimos para AdministradorDB.

SET ECHO OFF;

BEGIN
    FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'EQ_REMOTE_ADM') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    EXECUTE IMMEDIATE 'DROP USER EQ_REMOTE_ADM CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER EQ_REMOTE_ADM IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_EQUIPES_GESTAO
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_EQUIPES_GESTAO;

GRANT CREATE SESSION TO EQ_REMOTE_ADM;

GRANT SELECT ON EQ_OWNER.VW_AUDITORIA_SESSOES_LOCAL TO EQ_REMOTE_ADM;
GRANT SELECT ON EQ_OWNER.SESSAO_FUNCIONARIO_LOCAL TO EQ_REMOTE_ADM;
GRANT SELECT ON EQ_OWNER.MV_FUNCIONARIO_LOCAL TO EQ_REMOTE_ADM;
GRANT EXECUTE ON EQ_OWNER.PRC_REFRESH_FUNCIONARIO_LOCAL TO EQ_REMOTE_ADM;
GRANT EXECUTE ON EQ_OWNER.PRC_FECHAR_SESSAO_FUNC_LOCAL TO EQ_REMOTE_ADM;
