SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Funcionario'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Ponto_Distribuicao'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Historico_Manutencao'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Parametro_Qualidade'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM PRC_REG_PARAM_QUALIDADE_EQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Seq_Parametro_Qualidade'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM Parametro_Qualidade'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM PRC_REG_PARAM_QUALIDADE_EQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM TESTE_CONEXAO_DIST_CONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM TESTE_CONEXAO_DIST_CONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM TESTE_CONEXAO_TRANS_REC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM TESTE_CONEXAO_TRANS_REC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
    FOR r IN (
        SELECT object_name
        FROM user_objects
        WHERE object_type IN ('VIEW', 'PROCEDURE', 'FUNCTION', 'MATERIALIZED VIEW')
          AND object_name NOT LIKE 'BIN$%'
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM ' || r.object_name;
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

CREATE OR REPLACE SYNONYM Funcionario
FOR ADM_OWNER.FUNCIONARIO@DBLINK_ADMIN;

CREATE OR REPLACE SYNONYM Ponto_Distribuicao
FOR DIST_OWNER.VW_PONTO_DISTRIBUICAO@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM Historico_Manutencao
FOR DIST_OWNER.VW_HISTORICO_MANUTENCAO@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM Parametro_Qualidade
FOR TRANS_OWNER.PARAMETRO_QUALIDADE@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM PRC_REG_PARAM_QUALIDADE_EQ
FOR TRANS_OWNER.PRC_REG_PARAM_QUALIDADE_EQ@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM Seq_Parametro_Qualidade
FOR TRANS_OWNER.SEQ_PARAMETRO_QUALIDADE@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_DIST_CONS
FOR DUAL@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_TRANS_REC
FOR DUAL@DBLINK_TRANSF_REC;

CREATE OR REPLACE PUBLIC SYNONYM TESTE_CONEXAO_DIST_CONS
FOR EQ_OWNER.VW_TESTE_CONEXAO_DIST_CONS;

CREATE OR REPLACE PUBLIC SYNONYM TESTE_CONEXAO_TRANS_REC
FOR EQ_OWNER.VW_TESTE_CONEXAO_TRANS_REC;

DECLARE
    v_owner VARCHAR2(30) := USER;
BEGIN
    FOR r IN (
        SELECT object_name
        FROM user_objects
        WHERE object_type IN ('VIEW', 'PROCEDURE', 'FUNCTION', 'MATERIALIZED VIEW')
          AND object_name NOT LIKE 'BIN$%'
    ) LOOP
        EXECUTE IMMEDIATE 'CREATE PUBLIC SYNONYM ' || r.object_name || ' FOR ' || v_owner || '.' || r.object_name;
    END LOOP;
END;
/

CREATE OR REPLACE PUBLIC SYNONYM VW_LOGIN_FUNCIONARIO_LOCAL
FOR EQ_OWNER.VW_LOGIN_FUNCIONARIO_LOCAL;
