SET ECHO OFF;

CREATE TABLESPACE TS_EQUIPES_GESTAO
DATAFILE '/usr/lib/oracle/xe/oradata/XE/ts_equipes_gestao01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 25M MAXSIZE 250M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
