SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_FUNCIONARIO_LOCAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_LOGIN_FUNCIONARIO_LOCAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_ALERTA_QUALIDADE_AGUA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_TESTE_CONEXAO_DIST_CONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_TESTE_CONEXAO_TRANS_REC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE OR REPLACE VIEW VW_FUNCIONARIO_LOCAL AS
SELECT *
FROM MV_FUNCIONARIO_LOCAL;

CREATE OR REPLACE VIEW VW_LOGIN_FUNCIONARIO_LOCAL AS
SELECT cod_funcionario,
       codigo_no,
       nome_funcionario,
       username_oracle,
       estado_funcionario
  FROM MV_FUNCIONARIO_LOCAL;

CREATE OR REPLACE VIEW VW_ALERTA_QUALIDADE_AGUA AS
SELECT codigo_alerta,
       codigo_medicao,
       codigo_rh,
       mensagem_alerta,
       data_alerta
  FROM MV_ALERTA_QUALIDADE_AGUA;

CREATE OR REPLACE VIEW VW_TESTE_CONEXAO_DIST_CONS AS
SELECT 1 AS OK FROM TESTE_CONEXAO_DIST_CONS;

CREATE OR REPLACE VIEW VW_TESTE_CONEXAO_TRANS_REC AS
SELECT 1 AS OK FROM TESTE_CONEXAO_TRANS_REC;
