SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_recurso_hidrico'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_parametro_qualidade'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_medida_prot_responsavel'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_medida_proteccao'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_medicao_qualidade_agua'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_alerta_qualidade_agua'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_transferencia_cota'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE seq_recurso_hidrico START WITH 2000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_parametro_qualidade START WITH 900 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_medida_prot_responsavel START WITH 400 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_medida_proteccao START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_medicao_qualidade_agua START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_alerta_qualidade_agua START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_transferencia_cota START WITH 7000 INCREMENT BY 1 NOCACHE NOCYCLE;
