SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP USER FAM_FUNC_02 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER FAM_FUNC_01 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER APP_LOGIN_FAM CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER FAM_OWNER CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER E20240629 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE R_FAM_FUNC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE USER FAM_OWNER IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_FAMILIAS_COTAS
TEMPORARY TABLESPACE TEMP
QUOTA 400M ON TS_FAMILIAS_COTAS;

GRANT CREATE SESSION TO FAM_OWNER WITH ADMIN OPTION;
GRANT CREATE TABLE TO FAM_OWNER;
GRANT CREATE VIEW TO FAM_OWNER;
GRANT CREATE SEQUENCE TO FAM_OWNER;
GRANT CREATE PROCEDURE TO FAM_OWNER;
GRANT CREATE TRIGGER TO FAM_OWNER;
GRANT CREATE SNAPSHOT TO FAM_OWNER;
GRANT CREATE DATABASE LINK TO FAM_OWNER;
GRANT CREATE SYNONYM TO FAM_OWNER;
GRANT CREATE PUBLIC SYNONYM TO FAM_OWNER;
GRANT DROP PUBLIC SYNONYM TO FAM_OWNER;
GRANT CREATE USER TO FAM_OWNER;
GRANT ALTER USER TO FAM_OWNER;

CREATE ROLE R_FAM_FUNC;

GRANT R_FAM_FUNC TO FAM_OWNER WITH ADMIN OPTION;

CREATE USER APP_LOGIN_FAM IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_FAMILIAS_COTAS
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_FAMILIAS_COTAS;

GRANT CREATE SESSION TO APP_LOGIN_FAM;

CREATE USER FAM_FUNC_01 IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_FAMILIAS_COTAS
TEMPORARY TABLESPACE TEMP   
QUOTA 0K ON TS_FAMILIAS_COTAS;

CREATE USER FAM_FUNC_02 IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_FAMILIAS_COTAS
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_FAMILIAS_COTAS;

GRANT CREATE SESSION TO FAM_FUNC_01;
GRANT CREATE SESSION TO FAM_FUNC_02;

GRANT R_FAM_FUNC TO FAM_FUNC_01;
GRANT R_FAM_FUNC TO FAM_FUNC_02;
