SET ECHO OFF;

GRANT SELECT ON MV_FUNCIONARIO_LOCAL TO R_FAM_FUNC;
GRANT SELECT ON VW_FUNC_FAM_COTAS_LOCAL TO R_FAM_FUNC;
GRANT EXECUTE ON PRC_VALIDAR_FUNC_LOCAL TO R_FAM_FUNC;

BEGIN
    FOR r IN (
        SELECT object_name
        FROM user_objects
        WHERE object_type = 'VIEW'
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'GRANT SELECT ON ' || r.object_name || ' TO R_FAM_FUNC';
            EXECUTE IMMEDIATE 'GRANT SELECT ON ' || r.object_name || ' TO FAM_FUNC_01';
            EXECUTE IMMEDIATE 'GRANT SELECT ON ' || r.object_name || ' TO FAM_FUNC_02';
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

BEGIN
    FOR r IN (
        SELECT object_name
        FROM user_objects
        WHERE object_type IN ('PROCEDURE', 'FUNCTION')
    ) LOOP
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON ' || r.object_name || ' TO R_FAM_FUNC';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON ' || r.object_name || ' TO FAM_FUNC_01';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON ' || r.object_name || ' TO FAM_FUNC_02';
    END LOOP;
END;
/

GRANT SELECT ON FAM_OWNER.VW_LOGIN_FUNCIONARIO_LOCAL TO APP_LOGIN_FAM;
GRANT SELECT ON FAM_OWNER.VW_TESTE_CONEXAO_DIST_CONS TO R_FAM_FUNC;
GRANT SELECT ON FAM_OWNER.VW_TESTE_CONEXAO_TRANS_REC TO R_FAM_FUNC;

SET ECHO OFF;
