SET ECHO OFF;

-- Utilizador remoto e grants minimos para DistribuicaoConsumoDB.

BEGIN
    FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'FAM_REMOTE_DIST') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    EXECUTE IMMEDIATE 'DROP USER FAM_REMOTE_DIST CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER FAM_REMOTE_DIST IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_FAMILIAS_COTAS
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_FAMILIAS_COTAS;

GRANT CREATE SESSION TO FAM_REMOTE_DIST;

GRANT SELECT ON FAM_OWNER.VW_FAMILIA_BENEFICIARIA TO FAM_REMOTE_DIST;
GRANT SELECT ON FAM_OWNER.VW_COTA_AGUA TO FAM_REMOTE_DIST;
GRANT SELECT ON FAM_OWNER.VW_COTA_AGUA_STATUS TO FAM_REMOTE_DIST;
GRANT SELECT ON FAM_OWNER.VW_FAMILIA_COTA TO FAM_REMOTE_DIST;
GRANT SELECT ON FAM_OWNER.VW_FAMILIAS_POR_PONTO TO FAM_REMOTE_DIST;

GRANT EXECUTE ON FAM_OWNER.PRC_PRE_VALIDAR_COTA_RET TO FAM_REMOTE_DIST;
GRANT EXECUTE ON FAM_OWNER.PRC_DEBITAR_COTA_RETIRADA TO FAM_REMOTE_DIST;
