SET ECHO OFF;

-- Utilizador remoto e grants minimos para TransferenciasRecursosDB.

BEGIN
    FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'FAM_REMOTE_TRANS') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    EXECUTE IMMEDIATE 'DROP USER FAM_REMOTE_TRANS CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER FAM_REMOTE_TRANS IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_FAMILIAS_COTAS
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_FAMILIAS_COTAS;

GRANT CREATE SESSION TO FAM_REMOTE_TRANS;

GRANT SELECT ON FAM_OWNER.VW_FAMILIA_BENEFICIARIA TO FAM_REMOTE_TRANS;
GRANT SELECT ON FAM_OWNER.VW_COTA_AGUA TO FAM_REMOTE_TRANS;
GRANT EXECUTE ON FAM_OWNER.PRC_PRE_VALIDAR_TRANSF_COTA TO FAM_REMOTE_TRANS;
GRANT EXECUTE ON FAM_OWNER.PRC_APLICAR_TRANSF_COTA TO FAM_REMOTE_TRANS;
