SET ECHO OFF;

-- Guarda sessoes funcionais abertas no no local.

BEGIN EXECUTE IMMEDIATE 'DROP TABLE SESSAO_FUNCIONARIO_LOCAL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SESSAO_FUNC_LOCAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE SESSAO_FUNCIONARIO_LOCAL (
    codigo_sessao      NUMBER(7) NOT NULL,
    cod_funcionario    NUMBER(7) NOT NULL,
    codigo_no          NUMBER(7) NOT NULL,
    data_inicio        DATE DEFAULT SYSDATE NOT NULL,
    data_fim           DATE NULL,
    estado_sessao      VARCHAR2(20) DEFAULT 'ABERTA' NOT NULL,
    modo_login         VARCHAR2(20) DEFAULT 'ONLINE' NOT NULL
);

ALTER TABLE SESSAO_FUNCIONARIO_LOCAL ADD CONSTRAINT pk_sessao_func_local PRIMARY KEY (codigo_sessao);
ALTER TABLE SESSAO_FUNCIONARIO_LOCAL ADD CONSTRAINT ck_sessao_func_local_estado CHECK (estado_sessao IN ('ABERTA', 'FECHADA', 'EXPIRADA'));
ALTER TABLE SESSAO_FUNCIONARIO_LOCAL ADD CONSTRAINT ck_sessao_func_local_modo CHECK (modo_login IN ('ONLINE', 'OFFLINE'));

CREATE UNIQUE INDEX uk_sessao_func_local_aberta
    ON SESSAO_FUNCIONARIO_LOCAL (
        CASE WHEN estado_sessao = 'ABERTA' THEN cod_funcionario ELSE NULL END
    );

CREATE SEQUENCE SEQ_SESSAO_FUNC_LOCAL START WITH 1 INCREMENT BY 1 NOCACHE;
