SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Funcionario'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Ponto_Distribuicao'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Registro_Consumo'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM PRC_VALIDAR_PONTO_FAMILIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM FN_EXISTE_CONSUMO_FAMILIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM Transferencia_Cota'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM FAMILIA_DOA_REC_TRANSFER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM TRANSFER_ASSOC_COTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM FN_EXISTE_TRANSFER_FAMILIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM PRC_TRANSFERIR_COTA_TRANS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM PRC_TRANSFERIR_COTA';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM TESTE_CONEXAO_DIST_CONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM TESTE_CONEXAO_DIST_CONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM TESTE_CONEXAO_TRANS_REC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM TESTE_CONEXAO_TRANS_REC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
    FOR r IN (
        SELECT object_name
        FROM user_objects
        WHERE object_type IN ('VIEW', 'PROCEDURE', 'FUNCTION', 'MATERIALIZED VIEW')
          AND object_name NOT LIKE 'BIN$%'
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM ' || r.object_name;
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

CREATE OR REPLACE SYNONYM Funcionario
FOR ADM_OWNER.FUNCIONARIO@DBLINK_ADMIN;

CREATE OR REPLACE SYNONYM Ponto_Distribuicao
FOR DIST_OWNER.VW_PONTO_DISTRIBUICAO@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM Registro_Consumo
FOR DIST_OWNER.VW_REGISTRO_CONSUMO@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM PRC_VALIDAR_PONTO_FAMILIA
FOR DIST_OWNER.PRC_VALIDAR_PONTO_FAMILIA@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM FN_EXISTE_CONSUMO_FAMILIA
FOR DIST_OWNER.FN_EXISTE_CONSUMO_FAMILIA@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM Transferencia_Cota
FOR TRANS_OWNER.VW_TRANSFERENCIA_COTA@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM FAMILIA_DOA_REC_TRANSFER
FOR TRANS_OWNER.VW_FAMILIA_DOA_REC_TRANSFER@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM TRANSFER_ASSOC_COTA
FOR TRANS_OWNER.VW_TRANSFER_ASSOC_COTA@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM FN_EXISTE_TRANSFER_FAMILIA
FOR TRANS_OWNER.FN_EXISTE_TRANSFER_FAMILIA@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM PRC_TRANSFERIR_COTA_TRANS
FOR TRANS_OWNER.PRC_TRANSFERIR_COTA@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_DIST_CONS
FOR DUAL@DBLINK_DIST_CONS;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_TRANS_REC
FOR DUAL@DBLINK_TRANSF_REC;

CREATE OR REPLACE PUBLIC SYNONYM TESTE_CONEXAO_DIST_CONS
FOR FAM_OWNER.VW_TESTE_CONEXAO_DIST_CONS;

CREATE OR REPLACE PUBLIC SYNONYM TESTE_CONEXAO_TRANS_REC
FOR FAM_OWNER.VW_TESTE_CONEXAO_TRANS_REC;

DECLARE
    v_total NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_total
      FROM user_objects
     WHERE object_name = 'MV_FUNCIONARIO_LOCAL'
       AND object_type = 'MATERIALIZED VIEW';

    IF v_total > 0 THEN
        DBMS_SNAPSHOT.REFRESH('MV_FUNCIONARIO_LOCAL', 'C');
    END IF;
END;
/

DECLARE
    v_owner VARCHAR2(30) := USER;
BEGIN
    FOR r IN (
        SELECT object_name
        FROM user_objects
        WHERE object_type IN ('VIEW', 'PROCEDURE', 'FUNCTION', 'MATERIALIZED VIEW')
          AND object_name NOT LIKE 'BIN$%'
    ) LOOP
        EXECUTE IMMEDIATE 'CREATE PUBLIC SYNONYM ' || r.object_name || ' FOR ' || v_owner || '.' || r.object_name;
    END LOOP;
END;
/

CREATE OR REPLACE PUBLIC SYNONYM VW_LOGIN_FUNCIONARIO_LOCAL
FOR FAM_OWNER.VW_LOGIN_FUNCIONARIO_LOCAL;
