SET ECHO OFF;

CREATE TABLESPACE TS_FAMILIAS_COTAS
DATAFILE '/usr/lib/oracle/xe/oradata/XE/ts_familias_cotas01.dbf'
SIZE 150M
AUTOEXTEND ON NEXT 25M MAXSIZE 400M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
