SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_comite'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_equipe_tecnica'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_ferramenta_manutencao'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_equipamento_analista'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_material_educador'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE seq_comite START WITH 300 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_equipe_tecnica START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_ferramenta_manutencao START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_equipamento_analista START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_material_educador START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
