SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_ponto_distribuicao'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_registro_consumo'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_historico_manutencao'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_historico_abastecimento'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_retirada_agua_pendente'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE seq_ponto_distribuicao START WITH 4000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_registro_consumo START WITH 8000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_historico_manutencao START WITH 500 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_historico_abastecimento START WITH 9000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_retirada_agua_pendente START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
