SET ECHO OFF;

BEGIN EXECUTE IMMEDIATE 'DROP USER DIST_FUNC_02 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER DIST_FUNC_01 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER APP_LOGIN_DIST CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER DIST_OWNER CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER E20240629 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE R_DIST_FUNC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE USER DIST_OWNER IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_DISTRIBUICAO_CONSUMO
TEMPORARY TABLESPACE TEMP
QUOTA 1536M ON TS_DISTRIBUICAO_CONSUMO;

GRANT CREATE SESSION TO DIST_OWNER WITH ADMIN OPTION;
GRANT CREATE TABLE TO DIST_OWNER;
GRANT CREATE VIEW TO DIST_OWNER;
GRANT CREATE SEQUENCE TO DIST_OWNER;
GRANT CREATE PROCEDURE TO DIST_OWNER;
GRANT CREATE TRIGGER TO DIST_OWNER;
GRANT CREATE SNAPSHOT TO DIST_OWNER;
GRANT CREATE DATABASE LINK TO DIST_OWNER;
GRANT CREATE SYNONYM TO DIST_OWNER;
GRANT CREATE PUBLIC SYNONYM TO DIST_OWNER;
GRANT DROP PUBLIC SYNONYM TO DIST_OWNER;
GRANT CREATE USER TO DIST_OWNER;
GRANT ALTER USER TO DIST_OWNER;

CREATE ROLE R_DIST_FUNC;

GRANT R_DIST_FUNC TO DIST_OWNER WITH ADMIN OPTION;

CREATE USER APP_LOGIN_DIST IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_DISTRIBUICAO_CONSUMO
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_DISTRIBUICAO_CONSUMO;

GRANT CREATE SESSION TO APP_LOGIN_DIST;

CREATE USER DIST_FUNC_01 IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_DISTRIBUICAO_CONSUMO
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_DISTRIBUICAO_CONSUMO;

CREATE USER DIST_FUNC_02 IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_DISTRIBUICAO_CONSUMO
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_DISTRIBUICAO_CONSUMO;

GRANT CREATE SESSION TO DIST_FUNC_01;
GRANT CREATE SESSION TO DIST_FUNC_02;

GRANT R_DIST_FUNC TO DIST_FUNC_01;
GRANT R_DIST_FUNC TO DIST_FUNC_02;
