SET ECHO OFF;

GRANT SELECT ON VW_PONTO_DISTRIBUICAO TO R_DIST_FUNC;
GRANT SELECT ON VW_REGISTRO_CONSUMO TO R_DIST_FUNC;
GRANT SELECT ON VW_HISTORICO_MANUTENCAO TO R_DIST_FUNC;
GRANT SELECT ON VW_HISTORICO_MANUTENCAO_DET TO R_DIST_FUNC;
GRANT SELECT ON VW_HISTORICO_ABASTECIMENTO TO R_DIST_FUNC;
GRANT SELECT ON VW_ABAST_EM_CURSO TO R_DIST_FUNC;
GRANT SELECT ON VW_ABAST_CANCELAVEL TO R_DIST_FUNC;
GRANT SELECT ON VW_ABAST_RECURSO_ABERTO TO R_DIST_FUNC;

GRANT SELECT ON VW_COMITE TO R_DIST_FUNC;
GRANT SELECT ON VW_COTA_AGUA_STATUS TO R_DIST_FUNC;
GRANT SELECT ON VW_FAMILIA_BENEFICIARIA TO R_DIST_FUNC;
GRANT SELECT ON VW_PONTOS_COMITE_ASSOC TO R_DIST_FUNC;
GRANT SELECT ON VW_PONTOS_POR_RECURSO TO R_DIST_FUNC;
GRANT SELECT ON VW_PONTOS_RECURSO_ASSOC TO R_DIST_FUNC;
GRANT SELECT ON VW_PONTOS_TEC_MANUT TO R_DIST_FUNC;
GRANT SELECT ON VW_RECURSO_HIDRICO TO R_DIST_FUNC;
GRANT SELECT ON VW_RETIRADA_AGUA_PENDENTE TO R_DIST_FUNC;
GRANT SELECT ON VW_TECNICO_MANUTENCAO TO R_DIST_FUNC;
GRANT SELECT ON VW_TECNICO_MANUTENCAO_OPCAO TO R_DIST_FUNC;

GRANT SELECT ON VW_TESTE_CONEXAO_FAM_COTAS TO R_DIST_FUNC;
GRANT SELECT ON VW_TESTE_CONEXAO_TRANS_REC TO R_DIST_FUNC;
GRANT SELECT ON VW_TESTE_CONEXAO_EQ_GESTAO TO R_DIST_FUNC;

GRANT EXECUTE ON PRC_PRE_ACT_REGISTRO_CONSUMO TO R_DIST_FUNC;
GRANT EXECUTE ON PRC_ACT_OBSERVACAO_REG_CONS TO R_DIST_FUNC;

GRANT EXECUTE ON PRC_PRE_ALT_EST_PONTO TO R_DIST_FUNC;
GRANT EXECUTE ON PRC_ALT_EST_PONTO TO R_DIST_FUNC;

GRANT EXECUTE ON PRC_PRE_ASSOC_PONTOS_RECURSO TO R_DIST_FUNC;
GRANT EXECUTE ON PRC_ASSOC_PONTOS_RECURSO TO R_DIST_FUNC;

GRANT EXECUTE ON PRC_PRE_ASSOC_PONTOS_COMITE TO R_DIST_FUNC;
GRANT EXECUTE ON PRC_ASSOC_PONTOS_COMITE TO R_DIST_FUNC;

GRANT EXECUTE ON PRC_PRE_REGISTAR_PONTO TO R_DIST_FUNC;
GRANT EXECUTE ON PRC_REGISTAR_PONTO TO R_DIST_FUNC;

GRANT EXECUTE ON PRC_PRE_REGISTAR_MANUT_PONTO TO R_DIST_FUNC;
GRANT EXECUTE ON PRC_REGISTAR_MANUT_PONTO TO R_DIST_FUNC;

GRANT EXECUTE ON PRC_PRE_REG_ABASTECIMENTO TO R_DIST_FUNC;
GRANT EXECUTE ON PRC_REG_ABASTECIMENTO TO R_DIST_FUNC;
GRANT EXECUTE ON PRC_FINALIZAR_ABAST TO R_DIST_FUNC;

GRANT EXECUTE ON PRC_PRE_CANCELAR_ABAST TO R_DIST_FUNC;
GRANT EXECUTE ON PRC_CANCELAR_ABAST TO R_DIST_FUNC;

GRANT EXECUTE ON PRC_PRE_VALIDAR_RETIRADA_AGUA TO R_DIST_FUNC;
GRANT EXECUTE ON PRC_RETIRAR_AGUA TO R_DIST_FUNC;
GRANT EXECUTE ON PRC_PROC_RETIRADAS_PEND TO R_DIST_FUNC;

GRANT EXECUTE ON PRC_ABRIR_SESSAO_FUNC_LOCAL TO R_DIST_FUNC;
GRANT EXECUTE ON PRC_FECHAR_SESSAO_FUNC_LOCAL TO R_DIST_FUNC;

SET ECHO OFF;

GRANT SELECT ON DIST_OWNER.VW_LOGIN_FUNCIONARIO_LOCAL TO APP_LOGIN_DIST;

SET ECHO OFF;
