SET ECHO ON;

-- Garante uma sessao Oracle por funcionario da aplicacao.

ALTER SYSTEM SET RESOURCE_LIMIT = TRUE;

BEGIN
    EXECUTE IMMEDIATE 'DROP PROFILE PERFIL_FUNCIONARIO_APP CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2380 THEN
            RAISE;
        END IF;
END;
/

CREATE PROFILE PERFIL_FUNCIONARIO_APP LIMIT
    SESSIONS_PER_USER 1;

ALTER USER DIST_FUNC_01 PROFILE PERFIL_FUNCIONARIO_APP;
ALTER USER DIST_FUNC_02 PROFILE PERFIL_FUNCIONARIO_APP;

SET ECHO OFF;
