-- Utilizador remoto e grants minimos para AdministradorDB.

SET ECHO OFF;

BEGIN
    FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'DIST_REMOTE_ADM') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    EXECUTE IMMEDIATE 'DROP USER DIST_REMOTE_ADM CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER DIST_REMOTE_ADM IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_DISTRIBUICAO_CONSUMO
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_DISTRIBUICAO_CONSUMO;

GRANT CREATE SESSION TO DIST_REMOTE_ADM;

GRANT SELECT ON DIST_OWNER.VW_PONTO_DISTRIBUICAO TO DIST_REMOTE_ADM;
GRANT SELECT ON DIST_OWNER.VW_REGISTRO_CONSUMO TO DIST_REMOTE_ADM;
GRANT SELECT ON DIST_OWNER.VW_HISTORICO_ABASTECIMENTO TO DIST_REMOTE_ADM;
GRANT SELECT ON DIST_OWNER.VW_AUDITORIA_SESSOES_LOCAL TO DIST_REMOTE_ADM;
GRANT SELECT ON DIST_OWNER.SESSAO_FUNCIONARIO_LOCAL TO DIST_REMOTE_ADM;
GRANT SELECT ON DIST_OWNER.MV_FUNCIONARIO_LOCAL TO DIST_REMOTE_ADM;
GRANT EXECUTE ON DIST_OWNER.PRC_REFRESH_FUNCIONARIO_LOCAL TO DIST_REMOTE_ADM;
GRANT EXECUTE ON DIST_OWNER.PRC_FECHAR_SESSAO_FUNC_LOCAL TO DIST_REMOTE_ADM;
