SET ECHO OFF;

-- Utilizador remoto e grants minimos para TransferenciasRecursosDB.

BEGIN
    FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'DIST_REMOTE_TRANS') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    EXECUTE IMMEDIATE 'DROP USER DIST_REMOTE_TRANS CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER DIST_REMOTE_TRANS IDENTIFIED BY "20240629"
DEFAULT TABLESPACE TS_DISTRIBUICAO_CONSUMO
TEMPORARY TABLESPACE TEMP
QUOTA 0K ON TS_DISTRIBUICAO_CONSUMO;

GRANT CREATE SESSION TO DIST_REMOTE_TRANS;

GRANT SELECT ON DIST_OWNER.VW_PONTO_DISTRIBUICAO TO DIST_REMOTE_TRANS;
GRANT SELECT ON DIST_OWNER.VW_HISTORICO_ABASTECIMENTO TO DIST_REMOTE_TRANS;
