SET ECHO OFF;

CREATE OR REPLACE SYNONYM Funcionario
FOR ADM_OWNER.FUNCIONARIO@DBLINK_ADMIN;

CREATE OR REPLACE SYNONYM Familia_Beneficiaria
FOR FAM_OWNER.VW_FAMILIA_BENEFICIARIA@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM Cota_Agua
FOR FAM_OWNER.VW_COTA_AGUA@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM Cota_Agua_Status
FOR FAM_OWNER.VW_COTA_AGUA_STATUS@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM Familia_Cota
FOR FAM_OWNER.VW_FAMILIA_COTA@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM Familias_Por_Ponto
FOR FAM_OWNER.VW_FAMILIAS_POR_PONTO@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM PRC_DEBITAR_COTA_RETIRADA
FOR FAM_OWNER.PRC_DEBITAR_COTA_RETIRADA@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM PRC_PRE_VALIDAR_COTA_RET
FOR FAM_OWNER.PRC_PRE_VALIDAR_COTA_RET@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM Recurso_Hidrico
FOR TRANS_OWNER.VW_RECURSO_HIDRICO@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM PRC_VALIDAR_RECURSO_DIST
FOR TRANS_OWNER.PRC_VALIDAR_RECURSO_DIST@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM Comite
FOR EQ_OWNER.VW_COMITE@DBLINK_EQ_GESTAO;

CREATE OR REPLACE SYNONYM Equipe_Tecnica
FOR EQ_OWNER.VW_EQUIPE_TECNICA@DBLINK_EQ_GESTAO;

CREATE OR REPLACE SYNONYM Tecnico_Manutencao
FOR EQ_OWNER.VW_TECNICO_MANUTENCAO@DBLINK_EQ_GESTAO;

CREATE OR REPLACE SYNONYM PRC_VALIDAR_COMITE_DIST
FOR EQ_OWNER.PRC_VALIDAR_COMITE_DIST@DBLINK_EQ_GESTAO;

CREATE OR REPLACE SYNONYM PRC_VALIDAR_TECNICO_MANUT_DIST
FOR EQ_OWNER.PRC_VALIDAR_TECNICO_MANUT_DIST@DBLINK_EQ_GESTAO;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_FAM_COTAS_REMOTO
FOR DUAL@DBLINK_FAM_COTAS;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_TRANS_REC_REMOTO
FOR DUAL@DBLINK_TRANSF_REC;

CREATE OR REPLACE SYNONYM TESTE_CONEXAO_EQ_GESTAO_REMOTO
FOR DUAL@DBLINK_EQ_GESTAO;

CREATE OR REPLACE PUBLIC SYNONYM VW_PONTO_DISTRIBUICAO
FOR DIST_OWNER.VW_PONTO_DISTRIBUICAO;

CREATE OR REPLACE PUBLIC SYNONYM VW_REGISTRO_CONSUMO
FOR DIST_OWNER.VW_REGISTRO_CONSUMO;

CREATE OR REPLACE PUBLIC SYNONYM VW_HISTORICO_MANUTENCAO
FOR DIST_OWNER.VW_HISTORICO_MANUTENCAO;

CREATE OR REPLACE PUBLIC SYNONYM VW_HISTORICO_MANUTENCAO_DET
FOR DIST_OWNER.VW_HISTORICO_MANUTENCAO_DET;

CREATE OR REPLACE PUBLIC SYNONYM VW_HISTORICO_ABASTECIMENTO
FOR DIST_OWNER.VW_HISTORICO_ABASTECIMENTO;

CREATE OR REPLACE PUBLIC SYNONYM VW_ABAST_EM_CURSO
FOR DIST_OWNER.VW_ABAST_EM_CURSO;

CREATE OR REPLACE PUBLIC SYNONYM VW_ABAST_CANCELAVEL
FOR DIST_OWNER.VW_ABAST_CANCELAVEL;

CREATE OR REPLACE PUBLIC SYNONYM VW_ABAST_RECURSO_ABERTO
FOR DIST_OWNER.VW_ABAST_RECURSO_ABERTO;

CREATE OR REPLACE PUBLIC SYNONYM VW_COMITE
FOR DIST_OWNER.VW_COMITE;

CREATE OR REPLACE PUBLIC SYNONYM VW_COTA_AGUA_STATUS
FOR DIST_OWNER.VW_COTA_AGUA_STATUS;

CREATE OR REPLACE PUBLIC SYNONYM VW_FAMILIA_BENEFICIARIA
FOR DIST_OWNER.VW_FAMILIA_BENEFICIARIA;

CREATE OR REPLACE PUBLIC SYNONYM VW_PONTOS_COMITE_ASSOC
FOR DIST_OWNER.VW_PONTOS_COMITE_ASSOC;

CREATE OR REPLACE PUBLIC SYNONYM VW_PONTOS_POR_RECURSO
FOR DIST_OWNER.VW_PONTOS_POR_RECURSO;

CREATE OR REPLACE PUBLIC SYNONYM VW_PONTOS_RECURSO_ASSOC
FOR DIST_OWNER.VW_PONTOS_RECURSO_ASSOC;

CREATE OR REPLACE PUBLIC SYNONYM VW_PONTOS_TEC_MANUT
FOR DIST_OWNER.VW_PONTOS_TEC_MANUT;

CREATE OR REPLACE PUBLIC SYNONYM VW_RECURSO_HIDRICO
FOR DIST_OWNER.VW_RECURSO_HIDRICO;

CREATE OR REPLACE PUBLIC SYNONYM VW_RETIRADA_AGUA_PENDENTE
FOR DIST_OWNER.VW_RETIRADA_AGUA_PENDENTE;

CREATE OR REPLACE PUBLIC SYNONYM VW_TECNICO_MANUTENCAO
FOR DIST_OWNER.VW_TECNICO_MANUTENCAO;

CREATE OR REPLACE PUBLIC SYNONYM VW_TECNICO_MANUTENCAO_OPCAO
FOR DIST_OWNER.VW_TECNICO_MANUTENCAO_OPCAO;

CREATE OR REPLACE PUBLIC SYNONYM PRC_PRE_ACT_REGISTRO_CONSUMO
FOR DIST_OWNER.PRC_PRE_ACT_REGISTRO_CONSUMO;

CREATE OR REPLACE PUBLIC SYNONYM PRC_ACT_OBSERVACAO_REG_CONS
FOR DIST_OWNER.PRC_ACT_OBSERVACAO_REG_CONS;

CREATE OR REPLACE PUBLIC SYNONYM PRC_PRE_ALT_EST_PONTO
FOR DIST_OWNER.PRC_PRE_ALT_EST_PONTO;

CREATE OR REPLACE PUBLIC SYNONYM PRC_ALT_EST_PONTO
FOR DIST_OWNER.PRC_ALT_EST_PONTO;

CREATE OR REPLACE PUBLIC SYNONYM PRC_PRE_ASSOC_PONTOS_RECURSO
FOR DIST_OWNER.PRC_PRE_ASSOC_PONTOS_RECURSO;

CREATE OR REPLACE PUBLIC SYNONYM PRC_ASSOC_PONTOS_RECURSO
FOR DIST_OWNER.PRC_ASSOC_PONTOS_RECURSO;

CREATE OR REPLACE PUBLIC SYNONYM PRC_PRE_ASSOC_PONTOS_COMITE
FOR DIST_OWNER.PRC_PRE_ASSOC_PONTOS_COMITE;

CREATE OR REPLACE PUBLIC SYNONYM PRC_ASSOC_PONTOS_COMITE
FOR DIST_OWNER.PRC_ASSOC_PONTOS_COMITE;

CREATE OR REPLACE PUBLIC SYNONYM PRC_PRE_REGISTAR_PONTO
FOR DIST_OWNER.PRC_PRE_REGISTAR_PONTO;

CREATE OR REPLACE PUBLIC SYNONYM PRC_REGISTAR_PONTO
FOR DIST_OWNER.PRC_REGISTAR_PONTO;

CREATE OR REPLACE PUBLIC SYNONYM PRC_PRE_REGISTAR_MANUT_PONTO
FOR DIST_OWNER.PRC_PRE_REGISTAR_MANUT_PONTO;

CREATE OR REPLACE PUBLIC SYNONYM PRC_REGISTAR_MANUT_PONTO
FOR DIST_OWNER.PRC_REGISTAR_MANUT_PONTO;

CREATE OR REPLACE PUBLIC SYNONYM PRC_PRE_REG_ABASTECIMENTO
FOR DIST_OWNER.PRC_PRE_REG_ABASTECIMENTO;

CREATE OR REPLACE PUBLIC SYNONYM PRC_REG_ABASTECIMENTO
FOR DIST_OWNER.PRC_REG_ABASTECIMENTO;

CREATE OR REPLACE PUBLIC SYNONYM PRC_FINALIZAR_ABAST
FOR DIST_OWNER.PRC_FINALIZAR_ABAST;

CREATE OR REPLACE PUBLIC SYNONYM PRC_PRE_CANCELAR_ABAST
FOR DIST_OWNER.PRC_PRE_CANCELAR_ABAST;

CREATE OR REPLACE PUBLIC SYNONYM PRC_CANCELAR_ABAST
FOR DIST_OWNER.PRC_CANCELAR_ABAST;

CREATE OR REPLACE PUBLIC SYNONYM PRC_PRE_VALIDAR_RETIRADA_AGUA
FOR DIST_OWNER.PRC_PRE_VALIDAR_RETIRADA_AGUA;

CREATE OR REPLACE PUBLIC SYNONYM PRC_RETIRAR_AGUA
FOR DIST_OWNER.PRC_RETIRAR_AGUA;

CREATE OR REPLACE PUBLIC SYNONYM PRC_PROC_RETIRADAS_PEND
FOR DIST_OWNER.PRC_PROC_RETIRADAS_PEND;

CREATE OR REPLACE PUBLIC SYNONYM PRC_ABRIR_SESSAO_FUNC_LOCAL
FOR DIST_OWNER.PRC_ABRIR_SESSAO_FUNC_LOCAL;

CREATE OR REPLACE PUBLIC SYNONYM PRC_FECHAR_SESSAO_FUNC_LOCAL
FOR DIST_OWNER.PRC_FECHAR_SESSAO_FUNC_LOCAL;

CREATE OR REPLACE PUBLIC SYNONYM TESTE_CONEXAO_FAM_COTAS
FOR DIST_OWNER.VW_TESTE_CONEXAO_FAM_COTAS;

CREATE OR REPLACE PUBLIC SYNONYM TESTE_CONEXAO_TRANS_REC
FOR DIST_OWNER.VW_TESTE_CONEXAO_TRANS_REC;

CREATE OR REPLACE PUBLIC SYNONYM TESTE_CONEXAO_EQ_GESTAO
FOR DIST_OWNER.VW_TESTE_CONEXAO_EQ_GESTAO;

CREATE OR REPLACE PUBLIC SYNONYM VW_LOGIN_FUNCIONARIO_LOCAL
FOR DIST_OWNER.VW_LOGIN_FUNCIONARIO_LOCAL;

SET ECHO OFF;
