SET ECHO OFF;

CREATE TABLESPACE TS_DISTRIBUICAO_CONSUMO
DATAFILE '/usr/lib/oracle/xe/oradata/XE/ts_distribuicao_consumo01.dbf'
SIZE 700M
AUTOEXTEND ON NEXT 100M MAXSIZE 1536M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
